name: Go Build & Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.21.1
          - 1.22.x
          - 1.23.x
          - 1.24.x
          - 1.25.x
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: |
          go.work
          **/go.mod
          **/go.sum

    - name: Build
      run: make

    - name: Test
      run: make test
